server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Rota principal
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Slug /certificado
    location /certificado {
        try_files $uri $uri/ /certificado/index.html;
    }

    # Servir assets com cache
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript text/html;
}
